name: Node Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 12
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        node-version: [10, 12, 14]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: npm build
        run: |
          npm ci
          npm run build
